#include <iostream>
#include <string>
#include <random>

using namespace std;

string randDNA(int seed,string bases,int n,int mean,float std , int num_guesses)
 {
		 int index=-1;
		 string letters=""; 
		 //int min=0; // This denotes the first index of the string array
	     if(bases =="")
              	   {
			return "";
		   }
		// int max=bases.size()-1; // This denotes the last index of the string array
		 
		 mt19937 eng1(seed); //The input for the random number generator
		 //uniform_int_distribution<> unifrm(min,max);
		  normal_distribution<float>norm(mean,std);

          for(int j=0;j<num_guesses;j++)
             {
				 bases="";
			 for(int i=0; i<n; i++) // This loop generates the amount of letters in the string
			 {
				 //index= unifrm(eng1); The random value generated by the prng [uniform_int_distribution] is placed into the index of the string
				 index=norm(eng1);
				 letters += bases[index];  // The letters generated are added into a string
				 cout <<endl;
			}
	 if (letters=="L1es}")
			   cout << "11111111111111111111111"<<endl;	
	if(letters!="L1es}")
	cout << " "<< endl;
 }
   return letters;
  }
